from typing import Any, Protocol

class Persistence(Protocol):
    def get(self, *args, **kwargs) -> Any: ...
    def set(self, table: str, rows: list[dict]) -> None: ...
    def update(self, *args, **kwargs) -> None: ...


