"""Add reddit_posts table

Revision ID: 34a8ad64d277
Revises: 5aff9101192a
Create Date: 2025-09-16 21:11:28.999618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a8ad64d277'
down_revision: Union[str, Sequence[str], None] = '5aff9101192a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('flair', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('selftext', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('upvote_ratio', sa.Float(), nullable=False),
    sa.Column('post_created', sa.DateTime(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_posts_run_id'), 'reddit_posts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_posts_run_id'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    # ### end Alembic commands ###
