"""update trade_input fields to JSONB

Revision ID: 600807f306a9
Revises: 8be02617122d
Create Date: 2025-11-24 23:49:04.104227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '600807f306a9'
down_revision: Union[str, Sequence[str], None] = '8be02617122d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert TEXT columns to JSONB with proper casting
    op.execute("""
        ALTER TABLE trade_inputs 
        ALTER COLUMN recommendations_json 
        TYPE jsonb 
        USING recommendations_json::jsonb
    """)
    
    op.execute("""
        ALTER TABLE trade_inputs 
        ALTER COLUMN prices_json 
        TYPE jsonb 
        USING prices_json::jsonb
    """)
    
    op.execute("""
        ALTER TABLE trade_inputs 
        ALTER COLUMN positions_json 
        TYPE jsonb 
        USING positions_json::jsonb
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert back to TEXT if needed
    op.execute("""
        ALTER TABLE trade_inputs 
        ALTER COLUMN recommendations_json 
        TYPE text 
        USING recommendations_json::text
    """)
    
    op.execute("""
        ALTER TABLE trade_inputs 
        ALTER COLUMN prices_json 
        TYPE text 
        USING prices_json::text
    """)
    
    op.execute("""
        ALTER TABLE trade_inputs 
        ALTER COLUMN positions_json 
        TYPE text 
        USING positions_json::text
    """)

    # ### end Alembic commands ###
