"""add a reddit_id col to reddit_posts and reddit_fileterd_posts

Revision ID: 6800764bdeea
Revises: efb7a5d8eaa5
Create Date: 2025-10-05 16:43:55.821219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6800764bdeea'
down_revision: Union[str, Sequence[str], None] = 'efb7a5d8eaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_filtered_posts', sa.Column('reddit_id', sa.String(), nullable=True))
    op.add_column('reddit_posts', sa.Column('reddit_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_posts', 'reddit_id')
    op.drop_column('reddit_filtered_posts', 'reddit_id')
    # ### end Alembic commands ###
