"""add final_recommendations

Revision ID: 82eb3697e01a
Revises: f940555e705d
Create Date: 2025-10-29 22:34:12.222977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82eb3697e01a'
down_revision: Union[str, Sequence[str], None] = 'f940555e705d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reddit_post_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_recommendations_run_id'), 'final_recommendations', ['run_id'], unique=False)
    op.create_index(op.f('ix_final_recommendations_ticker'), 'final_recommendations', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_recommendations_ticker'), table_name='final_recommendations')
    op.drop_index(op.f('ix_final_recommendations_run_id'), table_name='final_recommendations')
    op.drop_table('final_recommendations')
    # ### end Alembic commands ###
