"""add portfolio_plans table

Revision ID: 86ff6a5d75f1
Revises: a6e61b3c5046
Create Date: 2025-09-18 23:42:09.868958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ff6a5d75f1'
down_revision: Union[str, Sequence[str], None] = 'a6e61b3c5046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profits', sa.JSON(), nullable=False),
    sa.Column('time_horizon_days', sa.Integer(), nullable=False),
    sa.Column('risk_reward', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_plans_run_id'), 'portfolio_plans', ['run_id'], unique=False)
    op.create_index(op.f('ix_portfolio_plans_ticker'), 'portfolio_plans', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_plans_ticker'), table_name='portfolio_plans')
    op.drop_index(op.f('ix_portfolio_plans_run_id'), table_name='portfolio_plans')
    op.drop_table('portfolio_plans')
    # ### end Alembic commands ###
