"""add trade_inputs

Revision ID: 8be02617122d
Revises: 5516c9b83c12
Create Date: 2025-11-24 23:18:06.418071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be02617122d'
down_revision: Union[str, Sequence[str], None] = '5516c9b83c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('has_data', sa.Boolean(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_cash', sa.Float(), nullable=False),
    sa.Column('recommendations_json', sa.Text(), nullable=False),
    sa.Column('prices_json', sa.Text(), nullable=False),
    sa.Column('positions_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_inputs_run_id'), 'trade_inputs', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_inputs_run_id'), table_name='trade_inputs')
    op.drop_table('trade_inputs')
    # ### end Alembic commands ###
