"""add three recommendation tables

Revision ID: 8dab605a59a6
Revises: 8fb2bfe1a4f3
Create Date: 2025-09-16 23:12:03.948274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dab605a59a6'
down_revision: Union[str, Sequence[str], None] = '8fb2bfe1a4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dd_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reddit_post_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dd_recommendations_run_id'), 'dd_recommendations', ['run_id'], unique=False)
    op.create_index(op.f('ix_dd_recommendations_ticker'), 'dd_recommendations', ['ticker'], unique=False)
    op.create_table('news_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reddit_post_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_recommendations_run_id'), 'news_recommendations', ['run_id'], unique=False)
    op.create_index(op.f('ix_news_recommendations_ticker'), 'news_recommendations', ['ticker'], unique=False)
    op.create_table('yolo_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reddit_post_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yolo_recommendations_run_id'), 'yolo_recommendations', ['run_id'], unique=False)
    op.create_index(op.f('ix_yolo_recommendations_ticker'), 'yolo_recommendations', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yolo_recommendations_ticker'), table_name='yolo_recommendations')
    op.drop_index(op.f('ix_yolo_recommendations_run_id'), table_name='yolo_recommendations')
    op.drop_table('yolo_recommendations')
    op.drop_index(op.f('ix_news_recommendations_ticker'), table_name='news_recommendations')
    op.drop_index(op.f('ix_news_recommendations_run_id'), table_name='news_recommendations')
    op.drop_table('news_recommendations')
    op.drop_index(op.f('ix_dd_recommendations_ticker'), table_name='dd_recommendations')
    op.drop_index(op.f('ix_dd_recommendations_run_id'), table_name='dd_recommendations')
    op.drop_table('dd_recommendations')
    # ### end Alembic commands ###
