"""add reddit_filtered_posts table

Revision ID: 8fb2bfe1a4f3
Revises: 915fd085cdaa
Create Date: 2025-09-16 21:30:20.115000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb2bfe1a4f3'
down_revision: Union[str, Sequence[str], None] = '915fd085cdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_filtered_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('flair', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('selftext', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('upvote_ratio', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_filtered_posts_run_id'), 'reddit_filtered_posts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_filtered_posts_run_id'), table_name='reddit_filtered_posts')
    op.drop_table('reddit_filtered_posts')
    # ### end Alembic commands ###
