"""update reddit_posts table cols

Revision ID: 915fd085cdaa
Revises: 34a8ad64d277
Create Date: 2025-09-16 21:23:32.375218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '915fd085cdaa'
down_revision: Union[str, Sequence[str], None] = '34a8ad64d277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_posts', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('reddit_posts', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('reddit_posts', 'post_created')
    op.drop_column('reddit_posts', 'post_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_posts', sa.Column('post_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('reddit_posts', sa.Column('post_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('reddit_posts', 'url')
    op.drop_column('reddit_posts', 'created')
    # ### end Alembic commands ###
