"""add financial snapshots table

Revision ID: a6e61b3c5046
Revises: 8dab605a59a6
Create Date: 2025-09-18 22:15:10.356257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e61b3c5046'
down_revision: Union[str, Sequence[str], None] = '8dab605a59a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sma20', sa.Float(), nullable=False),
    sa.Column('sma50', sa.Float(), nullable=False),
    sa.Column('sma200', sa.Float(), nullable=False),
    sa.Column('atr14', sa.Float(), nullable=False),
    sa.Column('high_52w', sa.Float(), nullable=False),
    sa.Column('low_52w', sa.Float(), nullable=False),
    sa.Column('rsi14', sa.Float(), nullable=False),
    sa.Column('asof', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_snapshots_run_id'), 'financial_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_financial_snapshots_ticker'), 'financial_snapshots', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_snapshots_ticker'), table_name='financial_snapshots')
    op.drop_index(op.f('ix_financial_snapshots_run_id'), table_name='financial_snapshots')
    op.drop_table('financial_snapshots')
    # ### end Alembic commands ###
