"""reddit_filterd_posts id to Integer autoinc

Revision ID: f940555e705d
Revises: db430518ad64
Create Date: 2025-10-05 17:41:00.883273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f940555e705d'
down_revision: Union[str, Sequence[str], None] = 'db430518ad64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TABLE reddit_filtered_posts ALTER COLUMN id TYPE INTEGER USING id::integer"
    )
    # If you want to make it auto-incrementing (identity):
    op.execute(
        "ALTER TABLE reddit_filtered_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE reddit_filtered_posts ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )
    op.execute(
        "ALTER TABLE reddit_filtered_posts ALTER COLUMN id TYPE VARCHAR USING id::text"
    )